# .travis.yml
#
matrix:
    include:
        - language: cpp
          compiler:
              - g++
          branches:
              except:
                  - debian/precise
          before_install: ./scripts/ci/pre.sh
          script: ./scripts/ci/run.sh

    include:
        - language: node_js
          node_js:
              - node
          sudo: required

          services:
              - docker
          before_install:
              - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

          script:
            - docker exec -it emscripten ./emscripten-build.sh
